### ISSUE TITLE
Incompatible with 1.9

### ISSUE THREAD

**Issue by c0untzer0** [LGhassen/Scatterer#83] opened 2020-02-13 17:51 UTC
Seems like the current version is incompatible with the latest release (1.9).
From the start, the Oceans are not rendered (although the ground terrain effects on the bottom are there and excellent).
When going to any craft outside the atmosphere, the atmosphere of Kerbin will totally disappear.

I'm using the EVE plugin with it, but I've verified this also happens when EVE is removed.

**Comment by LGhassen** [comment] 2020-02-14 08:11
Can you confirm it doesn't work with opengl also?

**Comment by c0untzer0** [comment] 2020-02-14 17:49
Well, I'm not sure how to answer. If you mean if my computer is using OpenGL, the answer is yes. I have an Nvidia GTX 1080 with all libs installed.

(One side note as feedback: It seems the stock version now on 1.9 does a good job at diffusing shadows on the ground, and when Scatterer was activated the shadows got diffused too much, besides all other issues. Not sure if this is a controllable setting, but might be something to consider for next version.)

I wish I could help you with the new version, but my C# skills are not what they used to be (I'm more inclined to Python nowadays, and I am definitely ignorant when it comes to graphic effects development. I really miss those beautiful oceans and Scatterer effects!

**Comment by LGhassen** [comment] 2020-02-15 14:38
So the game starts by default in dx11, which due to major changes breaks scatterer for now.

However scatterer is reported working more or less fine on OpenGL, here is how to start in OpenGL: https://wiki.kerbalspaceprogram.com/wiki/Startup_parameters (it will be slower though)

**Comment by c0untzer0** [comment] 2020-02-16 03:21
Ok, I see what you mean now. I try forcing OpenGL and GLCore. Scatterer is working with them. However, I’m seeing issues (not sure if from GL or Scatterer): The main issue is that there’s A LOT of artifacts. For example, the edges of the Mun craters are too diffused and full of artifacts (as if the texture is placed at a wrong angle). The performance is not much of a problem mainly because my hardware is pretty beefy. 
I will have to wait until you have so time to re-work it to be compatible with dx11. 
Anyway, you have done a great job! There are some tweaks I would suggest to the looks of the mod, but all in all, it was a great visual improvement and should even be part of the game!

**Comment by Not-AriStienfeld** [comment] 2020-02-18 01:18
I am also having issues. water no longer shows up, and shadows are very buggy. the console reads non-stop errors (might be due to textures unlimited, but doughful

**Comment by ghasemieh** [comment] 2020-02-29 23:16
If you use dx12 you would see no problem.

**Comment by c0untzer0** [comment] 2020-03-01 20:53
Yes, forcing DX12 is making Scatterer work again.
@LGhassen I did have to tone down the RGB for scatterer atmo config to get a more realistic look with this new game version on Kerbin atmo (I recon other planets have the same issue).
Another thing that I've noticed is that shadows seem to be scattered globaly, which makes shadows on planets/moons without atmosphere look unrealistic.
Not sure how to fix that one.

Cheers

**Comment by LGhassen** [comment] 2020-03-02 12:36
@c0untzer0 thanks for the report, what does it mean "shadows are scattered globally"?

**Comment by c0untzer0** [comment] 2020-03-02 14:18
Ok. So, to be precise: I see the shadows of object on the surface of the Mun, for example, being diffused, as if the light hitting the object was being scattered by an atmosphere. This should not be the case in celestial bodies without atmosphere. Shadows on the Mun and Minmus, for example, should be quite sharp. In other words, Mun and Minmus, as well as other moons and asteroids, should have their own settings to turn off any “light scattering” (while still allowing eclipses, sun flares, etc).

**Comment by jrodrigv** [comment] 2020-03-08 22:50
@LGhassen I have been debugging Scatterer to find the root cause of the issue.

It seems the Far Camera has been removed. Only the Near one is present when running in DX11.

I have been trying possible solutions. The obvious one was to assign both Far and Near cameras to the one that still alive. 

It worked fine from a visual point of view but the performance is terrible when the camera is NOT under water. 

Might be due to the TweakFarCameraShadowCascades is now active always? If I remove the code adding this object then the performance is fine but under water view is broken.

**Comment by LGhassen** [comment] 2020-03-09 09:09
@jrodrigv I'm aware the cameras have been merged, it's in the official changelog of KSP.

Assigning both far and near cameras to the one that is still alive is a terrible idea, it's better to not use the far camera in DX11 mode and reorganize things around it, while keeping everything the same for the other modes where there are both cameras. In my opinion it's more likely you are getting a nullref spam somewhere destroying performance.

**Comment by jrodrigv** [comment] 2020-03-22 07:34
@LGhassen I think I finally managed to unify everything in a single camera. However, I think there is a blocker that I'm not sure if there is away to solve. In order to make it look close to the dual camera version I had to increase the farclip plane to a high number (like 100000) the problem is that this value is too high for the nearclip plane distance, causing all shadows to flicker due to Unity float precession limitations.

I'm not a unity expert so I hope you can find workarounds for this :)

**Comment by R-T-B** [comment] 2020-03-24 02:16
I also made a unified camera build, was unaware someone had.  I made a pull request if you want to collaborate and/or borrow code:

https://github.com/LGhassen/Scatterer/pull/87

**Comment by jrodrigv** [comment] 2020-03-24 07:06
Thanks @R-T-B I will do some testing using your PR :)

**Comment by R-T-B** [comment] 2020-03-25 05:59
The shadows on my pull request are now better, but even I will admit they are far from solved completely.  I think they are best disabled at present:  KSP offers at least basic terrain shadowing now anyways.  That'd be my advice to those using these builds.

**Comment by R-T-B** [comment] 2020-03-26 07:09
IS there any particular reason blackrack that you are using close fit shadows when ocean shaders are on?  Those are known to flicker in this situation.  Why can't we use stable fit?

Also is there any particular reason we can't just move the near clip plane forward a tad bit to reduce the problem, and then move it back as appropriate for menus, etc?

**Comment by LGhassen** [comment] 2020-03-26 13:29
When I did the ocean shadows stable fit wasn't working very well and caused a phantom cirlcle shadow to appear at the edges of the camera view on the ocean.

For the near clip plane, I already find that it clips objects fairly early in gameplay and don't want it to clip objects from even farther.

**Comment by R-T-B** [comment] 2020-03-26 18:29
I think stablefit may be worth it anyhow, especially if it allows us to revert the nearclip hackery.  Thoughts?

**Comment by LGhassen** [comment] 2020-03-26 19:07
I'll have to try it again and see

**Comment by R-T-B** [comment] 2020-03-27 00:47
Yeah, if you are testing now there is still that missing zero, work took over my soul today via remote desktop, lol...

You can still test ocean shadowing up close though.  I'll fix the missing zero now.

**Comment by R-T-B** [comment] 2020-03-28 07:43
@LGhassen, my code on my branch is basically stable and frozen right now.  I'd judge from this commit if I were you what is/isn't mergeworthy, anything past here will probably be workarounds to issues you need to fix properly in the shader (there are already a few, but I avoided it as much as I could).

**Comment by LGhassen** [comment] 2020-04-19 20:48
I released an updated version for 1.9, it maintains compatibility with 1.8 and fixes some other issues.

**Closed by LGhassen** 2020-04-19 20:48 UTC
