### ISSUE TITLE
KSP 1.10.0 - Karman Line now sharply visible when close to it. 

### ISSUE THREAD

**Issue by jmigreen** [LGhassen/Scatterer#102] opened 2020-07-14 21:48 UTC
Since the update, while Scatterer still works very well overall, there are a couple notable exceptions.  One of them is that the atmospheric edges of all worlds "karman line"  is visible where as beforehand the atmosphere smoothly faded into space. It looks as if the atmosphere just sharply ends. 

Screenshot attached of current state:
![screenshot3774](https://user-images.githubusercontent.com/48394879/87479534-938f0480-c623-11ea-833e-97998ffb4abd.png)
![screenshot3721](https://user-images.githubusercontent.com/48394879/87479953-4e1f0700-c624-11ea-815f-96bb18ee4fb5.png)

Screenshot of before: 
![screenshot3427](https://user-images.githubusercontent.com/48394879/87479787-faacb900-c623-11ea-9222-fe224d0051ae.png)
![screenshot2942](https://user-images.githubusercontent.com/48394879/87479988-60994080-c624-11ea-81e4-3d60da7b1e24.png)

**Comment by LGhassen** [comment] 2020-07-15 08:27
For the atmosphere I made a temporary fix here, for testing before I fix any other issues and making a full release: https://forum.kerbalspaceprogram.com/index.php?/topic/103963-wip18x-19x-scatterer-atmospheric-scattering-v00610-25042020/&do=findComment&comment=3813263

**Comment by jmigreen** [comment] 2020-07-15 10:23
Hi, thank you so much for the fast response. I know you've got a life outside of KSP. 

I have tested the new DLL, and can report the following:
1. It shows moderate improvement on Kerbin. The Karman line is much less visible.
2. Unfortunately, it seems this is limited to Kerbin, as Duna and Laythe still show the line pretty noticeably (although I looked at older screenshots and it appears that it was always _more_ visible there, so that may not be new. 
![screenshot3794](https://user-images.githubusercontent.com/48394879/87532817-9a516200-c68b-11ea-86ce-b43df688e390.png)
![screenshot3798](https://user-images.githubusercontent.com/48394879/87532857-a9d0ab00-c68b-11ea-8e8d-7c093c7c73df.png)

3. Unfortunately, the fix has created a new issue: Kerbin at night is completely black. No ambient light. 
![screenshot3800](https://user-images.githubusercontent.com/48394879/87534223-a0484280-c68d-11ea-9e87-aef00b371dba.png)

Kind Regards

**Comment by LGhassen** [comment] 2020-07-15 13:26
That has always been this way and is a different issue I'm well aware of.

What changed with 1.10 and what my above .dll fixes is that the stock atmosphere was no longer getting disabled, so you were getting stock sky on top of scatterer sky.

**Comment by jmigreen** [comment] 2020-07-15 15:43
Understood.  I think we can close this issue then.  Should I open a separate one about the new .dll causing a loss of ambient lighting at night (at least on Kerbin), or are you already tracking that one?  From: LGhassenSent: Wednesday, July 15, 2020 2:27 PMTo: LGhassen/ScattererCc: jmigreen; AuthorSubject: Re: [LGhassen/Scatterer] KSP 1.10.0 - Karman Line now sharply visible when close to it. (#102) That has always been this way and is a different issue I'm well aware of.What changed with 1.10 and what my above .dll fixes is that the stock atmosphere was no longer getting disabled, so you were getting stock sky on top of scatterer sky.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by LGhassen** [comment] 2020-07-16 13:34
Which loss of ambint light?

**Comment by jmigreen** [comment] 2020-07-16 22:07
![screenshot3800](https://user-images.githubusercontent.com/48394879/87727505-fb2a8880-c7b8-11ea-9c69-8075aa550f32.png)

I can do testing in more places if needed, but on Kerbin at night, there appears to be complete darkness. This goes away if I revert to the previous version of the .dll

**Comment by LGhassen** [comment] 2020-08-01 14:35
@jmigreen I'm unable to reproduce your complete darkness issue. Everything is working correctly here, I can still see at night.

**Comment by jmigreen** [comment] 2020-08-01 15:09
Ok, I will re-test and see if I can still reproduce in 1.10.1 and under what circumstances.

**Comment by jmigreen** [comment] 2020-08-16 01:16
I can reproduce, but it is intermittent:  The game will load fine, and after continued play this will eventually happen. Perhaps a memory leak then? 
It's not just kerbin at night, it's an ambient lighting issue. Only direct light is visible. Anything not directly illuminated is completely black.  Attaching new screenshots. 

![screenshot15](https://user-images.githubusercontent.com/48394879/90324392-44abf600-df66-11ea-8230-b244cf5ac410.png)
![screenshot14](https://user-images.githubusercontent.com/48394879/90324401-5b524d00-df66-11ea-9d86-e77f22cd6f6e.png)
![screenshot12](https://user-images.githubusercontent.com/48394879/90324407-62795b00-df66-11ea-9750-9b4cc7a3ee03.png)

Prior to the issue occurring, ambient lighting is ok even with the new DLL.   Reverting to the old DLL prevents the issue. It never occurs.

**Comment by LGhassen** [comment] 2020-08-16 08:41
Can you try to disable the option "disable scaled space ambient lighting" and play like that for a while to see if it eliminates the issue?

**Comment by jmigreen** [comment] 2020-08-17 16:22
Sure, I've made that change and will report back when I get a chance to do some testing later in the week.

**Comment by LGhassen** [comment] 2020-08-20 22:13
@jmigreen can you try scatterer 0.0630? Someone on the forum reported it fixed this issue.

**Comment by jmigreen** [comment] 2020-09-28 08:44
@LGhassen Tested with that setting change and it did indeed fix the issue. Will try the new version as well. Sorry for the delay.

**Comment by LGhassen** [comment] 2020-12-17 10:03
Closing this since it is fixed

**Closed by LGhassen** 2020-12-17 10:03 UTC
