### ISSUE TITLE
invisibilty of the ground, buildings, crafts ect

### ISSUE THREAD

**Issue by Ilikekerbals** [LGhassen/Scatterer#154] opened 2022-03-03 17:32 UTC
Basicly when i load in theres no ground and i can see very faint outlines of the ksc so basicly i dont know how to really explain it or do.

**Comment by LGhassen** [comment] 2022-03-03 22:38
Please provide logs, images and reproduction steps. If I can't reproduce the issue I can't help you.

**Comment by LGhassen** [comment] 2022-03-24 09:05
Probably you started the game in dx12?
In any case I'm closing the issue due to no info provided. You can reopen it when you add logs/images.

**Closed by LGhassen** 2022-03-24 09:05 UTC
