### ISSUE TITLE
Kopernicus rings render in front of Scatterer Atmospheres in scaledspace

### ISSUE THREAD

**Issue by GregroxMun** [LGhassen/Scatterer#184] opened 2022-09-29 16:24 UTC
![screenshot580](https://user-images.githubusercontent.com/9667986/193084922-657c85dd-1245-4f53-8df3-3772fb4aa785.png)

(ignore the fact that she's purple--look at the rings where they go behind the planet.)

From the surface of planets, rings usually render correctly (though the ring shadows in the atmosphere look suspicious to me)

![image](https://user-images.githubusercontent.com/9667986/193085732-d93f0ad3-a75e-4ad7-abe0-6ce262fee2c9.png)

**Comment by LGhassen** [comment] 2022-09-30 08:33
This is a duplicate of #53 

A well-known issue that is not straightforward to fix

**Closed by LGhassen** 2022-09-30 08:33 UTC
