### ISSUE TITLE
White Atmosphere

### ISSUE THREAD

**Issue by TheComputer314** [LGhassen/Scatterer#149] opened 2022-01-25 21:41 UTC
So I decided to do a clean reinstall of KSP, but when I reinstall the game, install scatterer through CKAN and open the game, it just got stuck on the main menu without registering any inputs. Launching the game again, the atmosphere is completely white.
![image](https://user-images.githubusercontent.com/70153520/151063846-4ec5c46c-7ed0-4f2a-a75e-5c199e71047c.png)
![image](https://user-images.githubusercontent.com/70153520/151064230-c266803c-aaa9-44e0-a59c-a972cb99049a.png)
On the first time, KSP.log was yelling that "ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed." and on the second time, KSP.log isn't showing anything specific from a quick glance. (I forgot to save the KSP.log from the first time)
[KSP.log](https://github.com/LGhassen/Scatterer/files/7937368/KSP.log)
GameData folder
![image](https://user-images.githubusercontent.com/70153520/151064444-87d5d6ca-53c1-4b42-bb04-7bd98808a4f4.png)

**Comment by TheComputer314** [comment] 2022-01-25 21:42
Might have something to do with https://github.com/LGhassen/Scatterer/issues/57

**Comment by WujekFoliarz** [comment] 2022-01-25 21:42
> Might have something to do with #57

yea it's the same issue

**Comment by TheVrSofa** [comment] 2022-01-25 21:55
Same issue, we are chatting ot the mod maker but it looks liek a weird issue. post your logs and will help find the problem.
also discribe how you came acrross the issue.

personally, it was an update from ckan for scatterer, now nothing will make it go other than deleting scatterer.  we reinstalled other versions and issue came back

**Comment by TheVrSofa** [comment] 2022-01-25 21:56
> So I decided to do a clean reinstall of KSP, but when I reinstall the game, install scatterer through CKAN and open the game, it just got stuck on the main menu without registering any inputs. Launching the game again, the atmosphere is completely white. ![image](https://user-images.githubusercontent.com/70153520/151063846-4ec5c46c-7ed0-4f2a-a75e-5c199e71047c.png) ![image](https://user-images.githubusercontent.com/70153520/151064230-c266803c-aaa9-44e0-a59c-a972cb99049a.png) On the first time, KSP.log was yelling that "ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed." and on the second time, KSP.log isn't showing anything specific from a quick glance. (I forgot to save the KSP.log from the first time) [KSP.log](https://github.com/LGhassen/Scatterer/files/7937368/KSP.log) GameData folder ![image](https://user-images.githubusercontent.com/70153520/151064444-87d5d6ca-53c1-4b42-bb04-7bd98808a4f4.png)

Same issue, we are chatting ot the mod maker but it looks liek a weird issue. post your logs and will help find the problem.
also discribe how you came acrross the issue.

personally, it was an update from ckan for scatterer, now nothing will make it go other than deleting scatterer. we reinstalled other versions and issue came back

issue link with mod chat bellow:
https://github.com/LGhassen/Scatterer/issues/57

**Comment by LGhassen** [comment] 2022-01-25 23:03
> So I decided to do a clean reinstall of KSP, but when I reinstall the game, install scatterer through CKAN and open the game, it just got stuck on the main menu without registering any inputs. Launching the game again, the atmosphere is completely white. ![image](https://user-images.githubusercontent.com/70153520/151063846-4ec5c46c-7ed0-4f2a-a75e-5c199e71047c.png) ![image](https://user-images.githubusercontent.com/70153520/151064230-c266803c-aaa9-44e0-a59c-a972cb99049a.png) On the first time, KSP.log was yelling that "ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed." and on the second time, KSP.log isn't showing anything specific from a quick glance. (I forgot to save the KSP.log from the first time) [KSP.log](https://github.com/LGhassen/Scatterer/files/7937368/KSP.log) GameData folder ![image](https://user-images.githubusercontent.com/70153520/151064444-87d5d6ca-53c1-4b42-bb04-7bd98808a4f4.png)

Can you redo a clean install but from github not ckan? If that doesn't work try 0.0828, make sure to delete scattererAtmosphereCache as well.

**Comment by TheComputer314** [comment] 2022-01-25 23:42
Reinstall of 0.0829 from Github, same issue. Made sure to save logs this time.
[KSP.log](https://github.com/LGhassen/Scatterer/files/7937922/KSP.log)
0.0828 works completely fine. 
![image](https://user-images.githubusercontent.com/70153520/151078200-369ba985-944b-4e16-9ee3-2f5749420e48.png)

**Comment by WujekFoliarz** [comment] 2022-01-25 23:44
> Reinstall of 0.0829 from Github, same issue. Made sure to save logs this time.
> [KSP.log](https://github.com/LGhassen/Scatterer/files/7937922/KSP.log)
> 0.0828 works completely fine. 
> ![image](https://user-images.githubusercontent.com/70153520/151078200-369ba985-944b-4e16-9ee3-2f5749420e48.png)
> 
>  

Try to zoom in on Duna, it will crash

**Comment by TheComputer314** [comment] 2022-01-26 01:28
> > Reinstall of 0.0829 from Github, same issue. Made sure to save logs this time.
> > [KSP.log](https://github.com/LGhassen/Scatterer/files/7937922/KSP.log)
> > 0.0828 works completely fine.
> > ![image](https://user-images.githubusercontent.com/70153520/151078200-369ba985-944b-4e16-9ee3-2f5749420e48.png)
> 
> Try to zoom in on Duna, it will crash

Duna doesn't crash on 0.0828 for me but it is VERY laggy compared to Kerbin.

**Comment by LGhassen** [comment] 2022-01-26 08:06
> Reinstall of 0.0829 from Github, same issue. Made sure to save logs this time. [KSP.log](https://github.com/LGhassen/Scatterer/files/7937922/KSP.log) 0.0828 works completely fine. ![image](https://user-images.githubusercontent.com/70153520/151078200-369ba985-944b-4e16-9ee3-2f5749420e48.png)

Thanks for confirming that a rollback does indeed fix this. This seems to be hardware dependent, will try to reproduce it with an old pc.

**Comment by LGhassen** [comment] 2022-01-28 17:31
@TheComputer314 try this https://github.com/LGhassen/Scatterer/issues/57#issuecomment-1024446520

**Comment by LGhassen** [comment] 2022-01-28 18:26
Should be fixed in 0.0830

**Closed by LGhassen** 2022-01-28 18:26 UTC

**Comment by MillsLite** [comment] 2024-02-03 08:50
For all future google searches I think I found a way to work around this (or a similar) error. I don't know what the cause is or what the true fix is but I managed to update scatter using this (very long) method using CKAN.

First delete the "ScattererAtmosphereCache" in your GameData folder.

In CKAN change the version number of "Scatterer", "Scatterer Default Config", and "Scatterer Sunflare" to v0.0772

Load KSP, load a save, press "alt+F10" and change any settings as low as possible

Then using the tracking station zoom into each celestial body with an atmosphere so that it fills the screen. If it looks white at any time try to revert to an earlier version.

Exit the game

Now go back to CKAN and change the versions to 0.0825, load KSP, load save, change settings, look at planets and leave.

now make a copy of the new "PluginData" folder within the new "ScattererAtmosphereCache" and rename the copy to something for your reference (you can leave the renamed copy in the Cache folder).

Do it all again with version 0.028, make a copy of PluginData, do it again with version 0.0830, make copy, do it again with version v0.0838.

Is this method stupid, hell yeah, does it take ages to load KSP so many times, absolutely, is it the most efficient way, I would bet money that it isn't. However, I now have KSP running with scatterer so I guess thats something. At this point you can up the graphics settings with alt+F10  to something more fitting.

At any point if the game freezes then you'll need to try again from the previous attempt by deleting the working PluginData folder and renaming your backup to "PluginData". Once the game freezes any planets that's weren't looked at will now have the white atmosphere and you won't be able to change it. If freezing is frequent try smaller version steps but this order was what worked for me. Godspeed.

**Comment by LGhassen** [comment] 2024-06-02 05:10
For everyone who gets this, this happens when the atmosphere generation takes a long time and windows thinks the gpu crashed (when it hasn't). You can change the windows setting to fix this as instructed here: https://www.intel.com/content/www/us/en/docs/oneapi/installation-guide-windows/2024-1/gpu-adjust-timeout-detection-and-recovery-setting.html


> GPU: Adjust Timeout Detection and Recovery Setting

> Timeout Detection and Recovery (TDR) is a Windows* OS feature that detects and resets graphics cards with response problems. This feature freezes and reboots operating systems.

> Windows resets GPUs if the compute kernels run longer than a few seconds. To avoid a device reset during long running kernels, increase the value of TDRDelay setting:

>    Open the Run dialog box by pressing Windows + R keys on your keyboard.

>    Type regedit and click OK to open the Registry Editor.

>    Navigate to the following path by expanding the folders on the left pane: HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\GraphicsDrivers

> If the TdrDelay key exists, double-click it and increase the value in the Value data field (such as 20 seconds or higher). Continue to Step 7.

> If the TdrDelay key does not exist, click on an empty space on the right pane and select New > DWORD (32-bit) Value. Continue to Step 5.

>    Name the key TdrDelay.

>    Double-click the key and enter a desired value in the Value data field (such as 20 seconds or higher).

>    Click OK to save the changes.

>    Close the Registry Editor and restart your computer for the changes to take effect.

> For more information, refer to [TDRDelay documentation](https://learn.microsoft.com/en-us/windows-hardware/drivers/display/tdr-registry-keys#tdrdelay).
