### ISSUE TITLE
TAA causing weird blurring on waterfall plumes

### ISSUE THREAD

**Issue by Rodg88** [LGhassen/Scatterer#159] opened 2022-04-13 15:55 UTC
Using 0.0834, TAA seems to be doing something weird with waterfall plumes for me, with fps at least in the 20-30s:

https://cdn.discordapp.com/attachments/794875695942860810/963819857395212318/unknown.png

https://cdn.discordapp.com/attachments/794875695942860810/963820228146495538/unknown.png (edited to actually add the 2nd image)

Disabling TAA in the scatterer settings stopped it from happening.

**Comment by LGhassen** [comment] 2022-04-13 18:43
Looks like it's just trails? If it's the case It's unfixable because waterfall plumes are transparencies that don't write to the depth buffer so their motion (or lack thereof) isn't estimated correctly, instead it assumes that's part of the surface behind, and it passes the color validation because the colors are close enough to the current frame's plume color.

Marked as "won't fix" but it's because I can't think of a way to fix.

Unless it's not trails then feel free to add more info.

**Comment by Rodg88** [comment] 2022-04-13 19:26
It was just the waterfall trails yeah. I'm happy with just playing without TAA.

**Comment by LGhassen** [comment] 2022-04-13 19:48
I didn't mean waterfall trails, I meant a trailing effect

**Comment by LGhassen** [comment] 2022-04-15 11:13
Hmm I saw a video of this and it seems like waterfall plumes may be generating motion vectors. May be fixable after all, I'll have to test

**Comment by LGhassen** [comment] 2022-04-15 15:26
@Rodg88 I locked the game at 25 fps and tested with waterfall and waterfall stock plumes, didn't get either of your issues.

I'm closing this unless you add a reliable way of reproducing it.

**Closed by LGhassen** 2022-04-15 15:26 UTC
Labels: bug
