### ISSUE TITLE
PC shuts down when splashing down

### ISSUE THREAD

**Issue by swavkulinski** [LGhassen/Scatterer#44] opened 2018-05-12 21:49 UTC
Hi,

This one is scary. 

Steps:
GIVEN Running on Windows 10, 16GB, i7, GTX 1080Ti 

AND (KSP version doesn't matter as I've observed this on 1.3, 1.3.1 and now 1.4.3)

AND Any corresponding version of Scatterer

WHEN splashing down (on Kerbin)  

THEN: PC just instantly shuts down.

No logs, no nothing.

Notice: If I disable Scatterer no such behaviour.

**Comment by LGhassen** [comment] 2018-05-14 11:52
There can't be no logs, the log should be there leading up to the crash. Please follow the instructions here https://forum.kerbalspaceprogram.com/index.php?/topic/103963-wip142-scatterer-atmospheric-scattering-v00331b-27042018/ under "How to report Issues" and do a proper bug report.

**Comment by inorton** [comment] 2018-05-14 13:02
I have to ask, is your PC running inside your command pod? the water might mess with things

**Comment by JellyKisses** [comment] 2018-07-29 09:01
I have had a problem similar; but not with KSP. My PC would shut down at any graphically intensive part of any game I played. It turns out, my power supply unit couldn't supply enough power to my computer during these intense parts. I am guessing that the water is at it's highest quality when you splash down Coupled with the splash effects, it probably would cause it to shut down. Hope this helps.

**Comment by LGhassen** [comment] 2018-10-27 10:39
Closing this due to lack of logs and inability for me to reproduce it.

**Closed by LGhassen** 2018-10-27 10:39 UTC
