### ISSUE TITLE
Scatter sunflare missing

### ISSUE THREAD

**Issue by trung78952** [LGhassen/Scatterer#113] opened 2020-12-24 20:58 UTC
KSP: 1.8.1 Windows 64bit
Problem: sunflare missing but still work in map 

Mods installed:
![image](https://user-images.githubusercontent.com/34473850/103104221-7a6d9380-4658-11eb-8e19-154a0f915d8b.png)

Reproduction steps:
sunflare disappear random 

![image](https://user-images.githubusercontent.com/34473850/103106102-48aef980-4665-11eb-8095-9ec5a4baec7b.png)
![image](https://user-images.githubusercontent.com/34473850/103106125-801da600-4665-11eb-924b-e582f36090cf.png)

Log:

**Comment by LGhassen** [comment] 2020-12-24 23:27
These are not reproduction steps. Try removing your mods and putting them back to find the cause.

**Comment by trung78952** [comment] 2020-12-25 04:38
> These are not reproduction steps. Try removing your mods and putting them back to find the cause.

Your mean is remove all mod or just scatter

**Comment by trung78952** [comment] 2020-12-25 04:56
> These are not reproduction steps. Try removing your mods and putting them back to find the cause.

I uses version for 1.8.0 not for 1.8.1 because when i update scatter will not work ocean and asmosphere disappear

**Comment by kurgut** [comment] 2021-04-30 20:34
Hi, It seems I've got the same issue, which for me was related to KSP ingame graphical settings.
I had render quality set to "fastest", try switch it back to "simple" at least, it worked for me.

https://github.com/LGhassen/Scatterer/issues/113

**Comment by LGhassen** [comment] 2021-05-15 20:07
Should be fixed in 0.0767: https://github.com/LGhassen/Scatterer/releases/tag/0.0767

**Closed by LGhassen** 2021-05-15 20:07 UTC
