### ISSUE TITLE
RSS / RSSVE / rescaled bodies shore issues

### ISSUE THREAD

**Issue by Theysen** [LGhassen/Scatterer#86] opened 2020-02-18 19:48 UTC
There is the following issue with 1.8.1 and scatterer in relation to using RSS and / or RSSVE:

Video showcasing the issue:
https://www.youtube.com/watch?v=byQSn_K5X8Y

The lines on the shores are showing their - what seems like - scaled space ocean rendering color. When traversing that specific cutoff as seen in the video, the shores do not change. 

This video was taken with ocean shaders **turned off**, the issue persists with ocean shaders turned on.

The configs for RSSVE - Earth look like this: 
https://github.com/KSP-RO/RSSVE/blob/master/RSSVE/Configs/Scatterer_Configs/Earth/Earth_Atmosphere.cfg

The Kopernicus config for Earth looks like this:
https://github.com/KSP-RO/RealSolarSystem/blob/master/GameData/RealSolarSystem/RSSKopernicus/Earth/Earth.cfg

From our former talks, turning specific values to their extremes did not get rid of that effect. 

Thank you in advance for  the effort, we'd greatly appreciate to be able to whether that issue stems from scatterer or is on the planet mod side.

**Comment by RCrockford** [comment] 2020-03-15 11:56
I have done a little investigation of this, it is caused by the AtmosphericLocalScatter shader.
The issue seems to be that the scattering mesh is somewhat lower (19.5m in my testing) than the ocean mesh. This causes shallow water to receive more scattering than it should.

This can be seen in the following image showing the scattering passes (composite from RenderDoc capture).

![image](https://user-images.githubusercontent.com/40358880/76700862-a3b5c800-66b3-11ea-9b08-60b2583a3f1d.png)

The left image is ocean pre-scatter. Centre is the extiction pass, note that shallow areas pass the depth test, while deeper areas fail. The scattering pass is then applied leading to the final incorrect result.

**Comment by LGhassen** [comment] 2020-03-16 10:28
Thanks @RCrockford, I see what is the issue now. I think this behaviour is related to a depth offset I made to the AtmosphericLocalScatter to avoid z-fighting. I will see if I can tune it better or make it configurable, but it may come down to choosing between z-fighting or this issue.

**Comment by RCrockford** [comment] 2020-03-16 11:49
FWIW I tried tuning the opengl threshold and it made no difference.
I think the only way to eliminate z-fighting and this would be to stencil the water and then use that to reject water pixels from the scattering pass.

**Comment by LGhassen** [comment] 2020-04-11 10:40
Opengl threshold is meant to fix some black artifacts in the scattering shader but has nothing to do with this issue.

I will look into it, if I can access the stencil buffer mid-rendering then it's a good solution, if it needs to be done in the depth pre-pass it's a no-go as the ocean is too expensive to render twice.

If the stencil buffer idea is unfeasible then I have an alternative solution and will try to get it in for the next release.

**Comment by siimav** [comment] 2020-04-11 10:42
Is the next release going to be for both 1.8 and 1.9 or 1.9-only?

**Comment by LGhassen** [comment] 2020-04-11 10:49
Probably 1.9 only, although the only major change I can tell is the unified camera. And since I support both Opengl with dual cameras and dx11 with unified camera, it might be "accidentally" retro-compatible with 1.8, I will have to actually test it and see.

**Comment by LGhassen** [comment] 2020-04-11 21:47
Coming back to our discussion, @siimav my work-in-progress version seems to be fully compatible with 1.8, normally it should stay that way until release.

@RCrockford  and @Theysen I have managed to fix this issue by setting the same depth Offset value for ocean and scattering (previously Ocean had no offset and scattering had the offset to minimize z-fighting with terrain), to me it seems to be fixed with the scatterer ocean. However for the stock ocean I don't have a solution yet, I don't have the source for it's shader so I cannot add a depth offset to it or make it write something to stencil buffer. I could add an option to disable the depth offset on the scattering shader but that will bring a lot of z-fighting.

**Comment by siimav** [comment] 2020-04-17 11:33
Thanks, are those changes already available on any of the branches?

**Comment by LGhassen** [comment] 2020-04-19 20:45
Should be fixed in the latest release. Can you guys confirm?

**Comment by LGhassen** [comment] 2020-04-23 12:14
I'm closing this issue, in case it persists please reopen it.

**Comment by siimav** [comment] 2020-04-23 12:14
Yes, the original issue is fixed now. On the other hand the shoreline now appears to have a ton of z fighting as shown [here](https://drive.google.com/open?id=13Ohmi6MlaYYfwdVbUkmK8p-mAMlHlBjc).

**Closed by LGhassen** 2020-04-23 12:14 UTC

**Comment by LGhassen** [comment] 2020-04-23 12:19
@siimav :
-Which versions of scatterer and KSP does z-fighting appear on?
-Which video mode? (dx11, opengl etc)
-Which versions don't have this?

**Comment by siimav** [comment] 2020-04-24 09:25
Did a bit more testing and this issue was already there on 0.055 version but was just masked a bit by the other shoreline artifacts. It also appears to be a lot worse with the new 16 bits-per-pixel Earth heightmap as the shorelines are a lot more shallow now. @RCrockford do you think we could work around that issue with just Kopernicus configs?

**Comment by LGhassen** [comment] 2020-04-24 09:29
@siimav do you have this in dx11 or in OpenGL? My personal suggestion for a fix would be to not touch the clip planes and reset them to stock values, last I checked RSS sets them to large values (which is understandable given the scales but depth precision suffers).

**Comment by siimav** [comment] 2020-04-24 09:30
DX11

**Comment by RCrockford** [comment] 2020-04-24 12:38
I have just tried with the clip planes reset in DX11 and it's still occuring to the same degree as before.

**Comment by RCrockford** [comment] 2020-04-24 13:07
I have also tried making the shoreline much steeper, with them tuned to have 20m cliffs (which also extend 20m below the water), I still get a fair amount of fighting, though less than before.

**Comment by LGhassen** [comment] 2020-04-24 13:29
I see, I think this is probably not z-fighting, but jittering due to precision issues in how the ocean surface is projected (which are probably fine in stock but exacerbated by RSS scale). I will see what I can do, probably best if you guys open a separate issue, copy paste the last few messages in there.
