### ISSUE TITLE
kerbin color abnormal

### ISSUE THREAD

**Issue by Aebestach** [LGhassen/Scatterer#156] opened 2022-03-09 16:13 UTC
![contrast_1](https://user-images.githubusercontent.com/64588584/157482507-f4c5569a-4870-4fc8-8edb-0e56a70f4ac3.jpg)
![contrast_2](https://user-images.githubusercontent.com/64588584/157482523-55fcb73c-63d2-4f1e-b550-c525c4cc5016.jpg)

Hi,another.
When I use Scatterer and kopernicus, Kerbin planet color has changed, and I am not very clear from which MOD problem (because I use Scatterer and kopernicus separately, there is no problem).
[KSP.zip](https://github.com/LGhassen/Scatterer/files/8216282/KSP.zip)
[Logs.zip](https://github.com/LGhassen/Scatterer/files/8216284/Logs.zip)

**Comment by Aebestach** [comment] 2022-03-09 16:15
Scatterer V0.0831
Kopernicus Release-85

**Comment by Aebestach** [comment] 2022-03-10 01:18
All of these options is set to 1 in Scatterer, then the problem is resolved.
![work](https://user-images.githubusercontent.com/64588584/157568017-d82c485f-9e5a-4926-bd11-25557130d93e.png)

**Comment by Aebestach** [comment] 2022-03-10 01:18
However, in normal conditions, the color will become a bit dark.
![pic](https://user-images.githubusercontent.com/64588584/157568049-f85ab90d-99bb-44b0-89a5-b066befc9957.jpg)

**Comment by Aebestach** [comment] 2022-03-10 01:53
And the problem with this color is randomly, may be different every time you open the game.

**Comment by LGhassen** [comment] 2022-03-10 10:39
What you're trying to say is that these adjustments don't work with Kopernicus. Got it.

**Comment by Aebestach** [comment] 2022-03-10 12:16
It is when Scatterer and Kopernicus use, the color of the Kerbin planet will exceed the color, and it is random. I am not very clear that Scatterer's question or Kopernicus, so I reported this Issue.

**Comment by LGhassen** [comment] 2022-03-11 13:47
This seems like a genuine issue when using scatterer+kopernicus. You can leave the issue open unless you found something else.

**Comment by R-T-B** [comment] 2022-04-05 20:22
Interesting.  I wonder if this could be Kopernicus's fault?  Truth be told I am very unfamiliar with a lot of the code still, so it could be lurking in our code base somewhere.  I will keep an eye out.

**Comment by LGhassen** [comment] 2022-04-06 10:12
@R-T-B kopernicus unloads the texture and loads it when needed as part of load on demand.
Scatterer modifies the texture, I have code to detect when kopernicus loads/unloads but it may be janky, other issues have been reported with it so technically the issue is on Scatterer's side.

**Comment by R-T-B** [comment] 2022-04-10 01:39
I see.  Thanks for updating me.  I released my other bugfixes as is since this seems to be on your end, rather than trying to do pointless code sleuthing.  Thanks.

**Comment by JS-Ryan** [comment] 2023-04-22 06:14
Same problem. The color is of high contrast. Water is insanely black.

**Comment by LGhassen** [comment] 2024-07-07 16:00
Fixed in the latest version

**Closed by LGhassen** 2024-07-07 16:00 UTC
Labels: bug
