### ISSUE TITLE
KSP 1.10 ocean and scatterer effects disappearing when launching from VAB or SPH

### ISSUE THREAD

**Issue by nddragoon** [LGhassen/Scatterer#103] opened 2020-07-25 21:45 UTC
Using Scatterer on 1.10, everything looks fine until trying to launch a rocket from the launchpad. the ocean disappears leaving just the blue ocean floor and all the effects from scatterer vanish. This carries over back to the tracking station and main menu once it happens, only way to fix this is restarting the game
![image](https://user-images.githubusercontent.com/54559451/88466802-b9bf6a80-ce95-11ea-81fb-f03218501f54.png)
Using EVE+SVE though it also happens withous SVE

**Comment by nddragoon** [comment] 2020-07-31 19:38
Did some more testing:

- It's not actually when launching from the launchpad or runway, but instead when launching from the VAB or SPH. loading a vessel from the runway or launchpad does not cause this bug
- Disabling ocean shaders prevents the ocean from disappearing, but the atmospheric effects still disappear until restarting the game.

**Comment by LGhassen** [comment] 2020-08-01 13:28
Can you include logs and test without other mods?

**Comment by nddragoon** [comment] 2020-08-01 20:13
After testing it without mods i seem to have figured out what causes it. It seems to be a problem with RCS Build Aid which doesn't work in 1.10. i haven't the most remote clue as to how it can possibly be related to scatterer, but removing it seems to fix the issue. here's a log with just the 2 mods in case it matters https://gist.github.com/nddragoon/0773220df0235d0f4ac0ac6b2de81495

**Comment by LGhassen** [comment] 2020-08-02 11:33
Thank you for figuring it out. I will test with RCS build aid and see if the issue is fixable on my side.

**Comment by LGhassen** [comment] 2020-08-02 12:50
I have tested your issue today by installing RCS build aid and scatterer on 1.10 and launching from VAB with scatterer's ocean shaders ON and didn't run into any issues. Perhaps there is a step you missed.

**Comment by LGhassen** [comment] 2020-12-16 19:16
Closing this due to being unable to reproduce it and no further reproduction steps suggested.

**Closed by LGhassen** 2020-12-16 19:16 UTC
