### ISSUE TITLE
Atmospheric effects (clouds etc.) appear independed from the actual atmosphere, oceans have evaporated

### ISSUE THREAD

**Issue by taykolikos** [LGhassen/Scatterer#46] opened 2018-05-27 21:54 UTC
I may have made some mistakes while downloading the mods but I deleted all the mods and re installed at least 5 times to minimize my errors and It kept on glitching.
[KSP_BUG.zip](https://github.com/LGhassen/Scatterer/files/2043065/KSP_BUG.zip)

**Comment by dolpodolpi** [comment] 2018-05-29 21:41
having this same exact issue, using EVE and SVE.

**Comment by LGhassen** [comment] 2018-05-30 09:38
This is a duplicate of #40

**Closed by LGhassen** 2018-05-30 09:38 UTC
