### ISSUE TITLE
KSP 1.9.1 RSS Support

### ISSUE THREAD

**Issue by jrodrigv** [LGhassen/Scatterer#93] opened 2020-04-28 18:03 UTC
Hi,

I have been testing the latest official release with RSS using the same previous configuration it seems it is not working properly. I know R-T-B release supports RSS with a RSSMode. But not sure this release requires a specific configuration for RSS.

![Kerbal Space Program 28_04_2020 19_59_08](https://user-images.githubusercontent.com/8292603/80521267-096fc200-898b-11ea-9fd8-6c18f71dd13a.png)
![Kerbal Space Program 28_04_2020 19_58_19](https://user-images.githubusercontent.com/8292603/80521285-1391c080-898b-11ea-92dc-279388db2a13.png)

**Comment by LGhassen** [comment] 2020-04-28 21:40
Latest version is working with RSS. You seem to be having another issue, however if you don't include logs or detailed issue description so I can't help you.

**Comment by jrodrigv** [comment] 2020-04-29 07:43
I will try to do a more minimalistic setup then, although the only change I need to do to have the camera clip plane broken is to switch Scatterer versions from RTB one to this one. And moving back to RTBs with RSSMode=true fixes the problem.

**Comment by LGhassen** [comment] 2020-04-29 16:53
Scatterer doesn't touch the camera clipping planes, so... you have to find out on your own

**Comment by LGhassen** [comment] 2020-05-30 10:30
@jrodrigv do you still have this issue?

**Comment by siimav** [comment] 2020-09-06 14:17
I can confirm that the issue still happens with latest RSSVE/Scatterer/EVE releases in both KSP 1.9 and 1.10.
Any suggestions on how to investigate this issue?

**Comment by LGhassen** [comment] 2020-09-06 20:42
@siimav I need reproduction steps. Last time I couldn't reproduce this with RSS

**Comment by siimav** [comment] 2020-09-06 21:37
I think RSS+dependencies, Scatterer, EVE and RSSVE should be enough to replicate the issue. It should already be visible in the space center scene.
I also did some further digging myself and it appears that setting `Camera 00` `nearClipPlane` to `2,000,000` will fix the issue. I don't really understand the camera system and thus I have no idea what else this change could mess up.

**Comment by jrodrigv** [comment] 2020-09-12 11:59
Hi guys. 

I just did a PR adding a RSSMode. I have a done a quick test using latest KSP 1.10.1,  KSP-RO/RSS, Kopernicus recompiled for KSP 1.10.1 and Scatterer. 

Everything worked as expected.

**Comment by CindyRIng** [comment] 2020-09-12 12:56
@jrodrigv Wow,great. I used RTB's scatterer dll with scatterer610's shader in ksp1.9 last week, every thing worked,but when i instead shader to scatterer630,scatterer effect was miss at 120km. It may be cause by ksp version. I'm very puzzle of how to get rid of these problem, until now i still use camclips to fix it,but it will make another problem what makes sunflare offset screen center.

**Comment by LGhassen** [comment] 2020-09-25 18:39
Soo... I played around today with RSS and RSSVE.
RSSVE has a patch which is supposed to improve the clip planes for RSS. Except it hasn't been updated for unified camera (KSP 1.9+ or so can't remember), therefore it results in the first 2 images that @jrodrigv posted. As I said before it is not a scatterer issue.

How to fix it: Go to "\GameData\RSSVE\Configs\Misc_Configs\RSSVE_RSS_Config.cfg"
Either delete everything or change the contents to:

@REALSOLARSYSTEM:FOR[RSSVE]:NEEDS[RealSolarSystem]
{
    %cam00FarClip = 1875000.0
}

**Comment by siimav** [comment] 2020-09-28 21:51
That does indeed fix the issues for Earth but Venus still has some odd camera artifacts between 35 and 55 km of altitude.

**Comment by LGhassen** [comment] 2020-12-16 19:17
Hi this issue is now fixed without modifying the clip planes (see here: https://github.com/LGhassen/Scatterer/issues/66).

**Closed by LGhassen** 2020-12-16 19:17 UTC

**Comment by Katniss218** [comment] 2021-02-07 13:32
I'm sad to report, that fix doesn't work.

I'm using Windows, Scatterer 0.0723, and I'm not forcing any DX or anything.

The only fix right now is to remove that file modifying the clipping planes.

**Comment by LGhassen** [comment] 2021-02-07 15:38
> 
> 
> I'm sad to report, that fix doesn't work.
> 
> I'm using Windows, Scatterer 0.0723, and I'm not forcing any DX or anything.
> 
> The only fix right now is to remove that file modifying the clipping planes.

I think you don't understand what the fix fixes

**Comment by jrodrigv** [comment] 2021-02-07 16:32
@Katniss218 I'm using Scatterer 0.0723 with RSSVE.

It works for me having the following on the RSSVE_RSS_Config.cfg file

```
//  ==================================================
//  Real Solar System patches:
//
//  • Fix the surface texture clipping on low orbital
//    altitudes.
//  ==================================================

@REALSOLARSYSTEM:FOR[RSSVE]:NEEDS[RealSolarSystem]
{
    %cam00FarClip = 1875000.0
    %cam01NearClip = 1249.0
    %cam01FarClip = 1875000.0
	%camSSDepth = -4
	%camSSFarClip = 100000000
	%camSSNearClip = 9
}

```
