### ISSUE TITLE
NRE during OnStart for flight scene with ProceduralParts installed

### ISSUE THREAD

**Issue by jwvanderbeck** [LGhassen/Scatterer#97] opened 2020-05-17 22:52 UTC
```
[EXC 13:04:34.340] NullReferenceException: Object reference not set to an instance of an object
    scatterer.DepthToDistanceCommandBuffer.Awake () (at <a822e9740b51404b897e7cf406e4df3f>:0)
    UnityEngine.DebugLogHandler:LogException(Exception, Object)
    ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
    UnityEngine.Object:Instantiate(Part, Vector3, Quaternion)
    DragCubeSystem:RenderProceduralDragCube(Part)
    ProceduralParts.ProceduralPart:UpdateDragCubes()
    ProceduralParts.ProceduralPart:OnPartColliderChanged()
    BaseEvent:Invoke(BaseEventDetails)
    Part:SendEvent(String, BaseEventDetails, Int32)
    ProceduralParts.ProceduralAbstractShape:ColliderChanged()
    ProceduralParts.ProceduralAbstractShape:RaiseModelAndColliderChanged()
    ProceduralParts.ProceduralAbstractSoRShape:WriteMeshes(LinkedList`1)
    ProceduralParts.ProceduralAbstractSoRShape:WriteMeshes(ProfilePoint[])
    ProceduralParts.ProceduralShapeCone:UpdateShape(Boolean)
    ProceduralParts.ProceduralPart:OnStart(StartState)
    Part:ModulesOnStart()
    <Start>d__297:MoveNext()
    UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

**Comment by DRVeyl** [comment] 2020-05-21 19:18
Highlighting the important bit:  Looks like scatterer.DepthToDistanceCommandBuffer is getting an Awake() call as a result of stock's DragCubeSystem.  This needs to not NRE.

**Comment by LGhassen** [comment] 2020-05-30 10:28
I tested this on the latest version of scatterer and Procedural parts and found no such issue.
I'm closing this, assuming you tested with the previous version of scatterer, if you can reproduce it on the latest version you can reopen the issue, and include full logs.

**Closed by LGhassen** 2020-05-30 10:28 UTC
